-- Digital Silt Passport — Supabase schema
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.reaches (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  canal_name text not null,
  division text not null default 'Meerut',
  start_rd_km numeric(10,3),
  end_rd_km numeric(10,3),
  status text not null default 'Normal' check (status in ('Normal','Moderate','Heavy','Critical','Silt Hotspot')),
  priority text not null default 'Routine' check (priority in ('Routine','Priority','Critical')),
  current_condition text,
  cleaning_method text,
  quantity numeric(14,3),
  lead_m numeric(12,2),
  lift_m numeric(12,2),
  disposal_details text,
  dressing_details text,
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.field_records (
  id uuid primary key default gen_random_uuid(),
  reach_id uuid not null references public.reaches(id) on delete cascade,
  work_year text not null,
  chainage_from_km numeric(10,3),
  chainage_to_km numeric(10,3),
  silt_depth_cm numeric(8,2),
  scrapping_cm numeric(8,2),
  quantity numeric(14,3),
  cleaning_method text,
  lead_m numeric(12,2),
  lift_m numeric(12,2),
  disposal_details text,
  dressing_details text,
  remarks text,
  recorded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.verifications (
  id uuid primary key default gen_random_uuid(),
  reach_id uuid not null references public.reaches(id) on delete cascade,
  field_record_id uuid references public.field_records(id) on delete cascade,
  verification_type text not null check (verification_type in ('Departmental Committee','District Administration Nominated Committee')),
  verified boolean not null default false,
  verification_date date,
  remarks text,
  verified_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  designation text,
  division text,
  role text not null default 'staff' check (role in ('staff','admin')),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  action text not null,
  table_name text not null,
  record_id uuid,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_field_records_reach on public.field_records(reach_id);
create index if not exists idx_field_records_year on public.field_records(work_year);
create index if not exists idx_verifications_reach on public.verifications(reach_id);
create index if not exists idx_audit_log_record on public.audit_log(record_id);

alter table public.reaches enable row level security;
alter table public.field_records enable row level security;
alter table public.verifications enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.audit_log enable row level security;

-- Public QR access: read-only.
create policy "public can read reaches"
on public.reaches for select
to anon, authenticated
using (true);

create policy "public can read field records"
on public.field_records for select
to anon, authenticated
using (true);

create policy "public can read verifications"
on public.verifications for select
to anon, authenticated
using (true);

-- Authenticated approved staff/admin can write.
create policy "approved staff can insert field records"
on public.field_records for insert
to authenticated
with check (
  exists (
    select 1 from public.staff_profiles p
    where p.user_id = auth.uid() and p.approved = true
  )
);

create policy "approved staff can update field records"
on public.field_records for update
to authenticated
using (
  exists (
    select 1 from public.staff_profiles p
    where p.user_id = auth.uid() and p.approved = true
  )
)
with check (
  exists (
    select 1 from public.staff_profiles p
    where p.user_id = auth.uid() and p.approved = true
  )
);

create policy "approved staff can insert verifications"
on public.verifications for insert
to authenticated
with check (
  exists (
    select 1 from public.staff_profiles p
    where p.user_id = auth.uid() and p.approved = true
  )
);

-- Staff may read their own profile; admin access should be tightened
-- further with a server-side function/claim in production.
create policy "users can read own profile"
on public.staff_profiles for select
to authenticated
using (user_id = auth.uid());

insert into public.reaches
(code, canal_name, division, start_rd_km, end_rd_km, status, priority, current_condition)
values
('KM-KITHORE-02400-03100','Kithore Minor','Meerut',2.400,3.100,'Silt Hotspot','Critical','Pilot reach — replace with verified field data')
on conflict (code) do nothing;
